apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dbvaultsources.dbvault.io
spec:
  group: dbvault.io
  scope: Namespaced
  names:
    plural: dbvaultsources
    singular: dbvaultsource
    kind: DBVaultSource
    shortNames: [dbvsrc]
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              required: [engine, repositoryRef, connection]
              properties:
                engine: {type: string, enum: [sqlite, postgres, mysql, mariadb]}
                repositoryRef:
                  type: object
                  required: [name]
                  properties:
                    name: {type: string}
                connection:
                  type: object
                  properties:
                    host: {type: string}
                    port: {type: integer}
                    database: {type: string}
                    username: {type: string}
                    sqlitePath: {type: string}
                    sslMode: {type: string}
                    passwordSecretRef:
                      type: object
                      properties:
                        name: {type: string}
                        key: {type: string}
                logicalBackup:
                  type: object
                  properties:
                    enabled: {type: boolean}
                    format: {type: string}
                physicalBackup:
                  type: object
                  properties:
                    enabled: {type: boolean}
                wal:
                  type: object
                  properties:
                    enabled: {type: boolean}
                    mode: {type: string}
                binlog:
                  type: object
                  properties:
                    enabled: {type: boolean}
                    mode: {type: string}
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
