apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dbvaultrestores.dbvault.io
spec:
  group: dbvault.io
  scope: Namespaced
  names:
    plural: dbvaultrestores
    singular: dbvaultrestore
    kind: DBVaultRestore
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              required: [sourceRef, target]
              properties:
                sourceRef:
                  type: object
                  required: [name]
                  properties:
                    name: {type: string}
                snapshotID: {type: string}
                targetTime: {type: string, format: date-time}
                restorePoint: {type: string}
                target:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                approval:
                  type: object
                  properties:
                    required: {type: boolean}
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
